VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "clsRingRc"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
'Public RDatum As Long
Public Rdatum As String
Public RTr As Long
Public Ring As String
Public Dnr As String
Public Centr As String
Public Idkull As String
Public Mnr As String
Public MarkarNamn As String
Public Lokal As String
Public Tr As String
Public Datum As String
Public Tnog As String
Public Artkod As String
Public Signatur As String
Public Sex As String
Public Age As String
Public Status As String
Public Varn As String
Public Pullus As String
Public Reserv As String
Public Vinge As String
Public Vikt As String
Public Fett As String
Public Pjm As String
Public Basdata As String
Public Maerkareut As String
Public Centralut As String
Public Extradata As String
Public Koordinat As String
Public Prov As String
Public Ort As String
Public Datafinns As Long
Public Rubrik As String
Public Fynddetalj As String
Public Longort As Boolean
Public Basdataut As Boolean
Public Helort As String
Public Ort2 As String
Public Märkdata As String

'Public visRing As String
'Public visCentr As String

